### ISSUE TITLE
视频可以设置速度 但是番剧无法设置速度 Chrome115谷歌浏览器测试

### ISSUE THREAD

**Issue by r0bbit** [NicerWang/Bili_Video_Speed_Controller#1]
视频可以设置速度 但是番剧无法设置速度 Chrome115谷歌浏览器测试 大哥什么时候方便看下 比如这个视频 https://www.bilibili.com/bangumi/play/ep765809 就没有自定义那几个字

**Comment by NicerWang** [comment]
你好，我更新了一下脚本（v0.4），目前`bangumi/play/`前缀的视频也能调整了。
